import random
import string


def generate_random_name(sylb=2):
    """Generate a random name following common English name tendencies."""
    vowels = "aeiou"
    consonants = "bcdfghjklmnpqrstvwxyz"
    syllables = [
        "ba",
        "be",
        "bi",
        "bo",
        "bu",
        "da",
        "de",
        "di",
        "do",
        "du",
        "fa",
        "fe",
        "fi",
        "fo",
        "fu",
        "ga",
        "ge",
        "gi",
        "go",
        "gu",
        "ha",
        "he",
        "hi",
        "ho",
        "hu",
        "ja",
        "je",
        "ji",
        "jo",
        "ju",
        "ka",
        "ke",
        "ki",
        "ko",
        "ku",
        "la",
        "le",
        "li",
        "lo",
        "lu",
        "ma",
        "me",
        "mi",
        "mo",
        "mu",
        "na",
        "ne",
        "ni",
        "no",
        "nu",
        "pa",
        "pe",
        "pi",
        "po",
        "pu",
        "ra",
        "re",
        "ri",
        "ro",
        "ru",
        "sa",
        "se",
        "si",
        "so",
        "su",
        "ta",
        "te",
        "ti",
        "to",
        "tu",
        "va",
        "ve",
        "vi",
        "vo",
        "vu",
        "wa",
        "we",
        "wi",
        "wo",
        "wu",
        "ya",
        "ye",
        "yi",
        "yo",
        "yu",
        "za",
        "ze",
        "zi",
        "zo",
        "zu",
    ]
    name = ""

    for i in range(sylb):
        name = name + random.choice(syllables)
        if random.random() < 0.1:
            name = name + random.choice(vowels)
        if random.random() < 0.1:
            name = name + random.choice(consonants)

    return "".join(name).capitalize()
